### ISSUE TITLE
Feature request: launch custom intent when clicking the upload notification

### ISSUE THREAD

**Issue by oguzhandongul** [alexbbb/android-upload-service#12]
We have an application and we are using your library in our app. We need to open application by  clicking the notification but it seems that the library is not supporting this feature. I tried to modify the library but it's not working. Will you add this feature in the library? Or can you show haw can we manage it?

**Comment by alexbbb** [comment]
@oguzhandongul the feature you requested has been implemented. Please update the library and give it a try :)
Usage example:
```java
UploadRequest request = new UploadRequest(this, "uploadId", "http://path/to/server");
...
request.setNotificationClickIntent(new Intent(this, YourActivity.class));
```
