### ISSUE TITLE
405 Error from Nginx/uWSGI

### ISSUE THREAD

**Issue by peterswang** [alexbbb/android-upload-service#17]
This worked with the PHP test script, where PHP runs behind Nginx.  I then configured uWSGI and a Python upload app to save the uploaded files.  But, that came back with "405 Not Allowed" error, after the file was sent to Nginx (see screenshot).
![screen shot 2015-02-02 at 4 23 20 pm](https://cloud.githubusercontent.com/assets/10738534/6012175/dafa7c78-aaf9-11e4-8aff-7e725940cc5b.png)

The Python method to save the file was never invoked.  After checking the Nginx and uWSGI configurations for a day without getting anywhere, I resorted to capturing the upload exchange with Wireshark.
![screen shot 2015-02-02 at 4 20 28 pm](https://cloud.githubusercontent.com/assets/10738534/6012219/5e9337f0-aafa-11e4-812d-48a8ac836304.png)

As you can see from the screenshot, there was a malformed packet error msg sent by the server (129.168.1.41) back to the Android client (129.168.1.79).  More detail in screenshot below, but nothing that gave useful clue.
![screen shot 2015-02-02 at 4 17 26 pm](https://cloud.githubusercontent.com/assets/10738534/6012267/f97c0d1e-aafa-11e4-9979-2ba9c7accb18.png)

Any idea what the issue might be?  Or how to track it down?

Thanks!

**Comment by peterswang** [comment]
Here's the screenshot from Nginx access and error log.
![screen shot 2015-02-02 at 4 51 44 pm](https://cloud.githubusercontent.com/assets/10738534/6012344/d55399d8-aafb-11e4-9ed1-2656738d604d.png)

**Comment by alexbbb** [comment]
It seems to me that your problem resides entirely on the server side and
has nothing to do with the android upload service. Try to ask the uWSGI
community and have a look here:
http://leandroardissone.com/post/19690882654/nginx-405-not-allowed
Il 03/feb/2015 01:54 "peterswang" <notifications@github.com> ha scritto:

**Comment by peterswang** [comment]
Thanks.  It did turn out to be Nginx/uWSGI configuration issues., though nothing to do with static pages.

**Comment by alexbbb** [comment]
Closing the issue as it's not an android upload service bug
