### ISSUE TITLE
Error on chunked responses

### ISSUE THREAD

**Issue by mywaystar** [alexbbb/android-upload-service#19]
When i use an node.js server with express, it's sets chunked responses by default.

Chunked responses don't seems to work with the InputStream

**Comment by alexbbb** [comment]
Please describe the case in which you get the error in detail, so I can try to reproduce it

**Comment by alexbbb** [comment]
@mywaystar are you using node.js + express + multer middleware to handle multipart form data?

**Comment by mywaystar** [comment]
Yes. Exactly. I resolved the problem wuth disabling chucked responses.

-----Message d'origine-----
De : "Alex Gotev" <notifications@github.com>
Envoyé : ‎24/‎02/‎2015 16:15
À : "alexbbb/android-upload-service" <android-upload-service@noreply.github.com>
Cc : "Baptiste JAMIN" <baptistejamin@gmail.com>
Objet : Re: [android-upload-service] Error on chunked responses (#19)

@mywaystar are you using node.js + express + multer middleware to handle multipart form data?

**Comment by alexbbb** [comment]
@mywaystar I'll try to replicate this behavior when I have some time. What are you sending to the client as a response? If you can, post here the server side node.js code that you use (without your business logic of course :D)

**Comment by alexbbb** [comment]
Added example node.js server script: android-upload-service/examples/server-nodejs/index.js

**Comment by alexbbb** [comment]
This solves the issue: http://stackoverflow.com/questions/24729329/node-js-disable-chunked-transfer-encoding
