### ISSUE TITLE
Feature request: retry failed uploads

### ISSUE THREAD

**Issue by stavarengo** [alexbbb/android-upload-service#21]
Hi Alex. Congratulations on this work.
I just started to use it and it was really easy to set it up.

Now I'm trying to create a behavior that shows a notification telling "Touch to retry" when the upload fails, however, I'm not finding a option for that.

Am I missing anything or android-upload-service indeed do not provides a way to do this?

**Comment by alexbbb** [comment]
Hi @stavarengo, you're not missing anything, because the feature of retrying an upload is not implemented in the library yet, though it would be a nice addition to have!

**Comment by alexbbb** [comment]
The feture has been implemented. To use it, update the library, and add this statement where you set the upload request:
```java
// set the maximum number of automatic upload retries on error
request.setMaxRetries(2);
```
