### ISSUE TITLE
Cannot compile with gradle

### ISSUE THREAD

**Issue by idanbar134** [alexbbb/android-upload-service#22]
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by alexbbb** [comment]
Are you using Android Studio? 
Try Build > Clean Project 
and then 
Build > Rebuild Project

**Comment by alexbbb** [comment]
@idanbar134 the proposed solution work for you?

**Comment by foodyi** [comment]
I had the same issue in andorid studo, i try to clean and rebuild, it could build successful. but when i debug project on device it will report the same error.

**Comment by foodyi** [comment]
I just import java source code to my project,it works well.

**Comment by idanbar134** [comment]
Hey )

Thanks. i fixed it) have great day bro


On Thu, Mar 12, 2015 at 8:51 AM, foodyi <notifications@github.com> wrote:

> I just import java source code to my project,it works well.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alexbbb/android-upload-service/issues/22#issuecomment-78431950>
> .
>



-- 
Idan Ayalon

**Comment by idanbar134** [comment]
Hi Alex,
How are you?

I'm trying to upload pictures in ssl to my server and i get an exception:
i use this line inside my uploadFileToServer method where i do all Requests.

 03-16 09:59:01.582  24782-24903/com.nuro E/com.newrelic.agent.android﹕
Failed to detect New Relic instrumentation.  Something likely went wrong
during your build process and you should contact support@newrelic.com.
03-16 09:59:27.094  24782-24782/com.nuro E/CliptrayUtils﹕
hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
03-16 10:00:08.093  24782-24782/com.nuro E/CliptrayUtils﹕
hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
03-16 10:00:16.895  24782-24782/com.nuro W/art﹕ Attempt to remove local
handle scope entry from IRT, ignoring
03-16 10:00:16.925  24782-24782/com.nuro W/chromium﹕
[WARNING:resource_bundle.cc(304)] locale_file_path.empty()
03-16 10:00:16.926  24782-25935/com.nuro W/AudioManagerAndroid﹕ Requires
BLUETOOTH permission
03-16 10:00:17.004  24782-24914/com.nuro W/OpenGLRenderer﹕ Trying to scale
down bitmap for texture (2880x5120 -> 2304x4096)
03-16 10:00:35.519  24782-24782/com.nuro W/TouchFlickNoti﹕
CAPP_TOUCH_FLICK: UP vectorVelocity:-9048 signal:-1
03-16 10:00:46.539  24782-24914/com.nuro W/OpenGLRenderer﹕ Trying to scale
down bitmap for texture (2880x5120 -> 2304x4096)
03-16 10:00:47.806  24782-24782/com.nuro E/ChatFragment﹕ Error in upload
with ID: 12fc87f6-8e5f-48e9-8d8b-85058d4629ce. Write error: ssl=0x9a2e1200:
I/O error during system call, Broken pipe
    javax.net.ssl.SSLException: Write error: ssl=0x9a2e1200: I/O error
during system call, Broken pipe
            at com.android.org.conscrypt.NativeCrypto.SSL_write(Native
Method)
            at
com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:740)
            at com.android.okio.Okio$1.write(Okio.java:70)
            at
com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at
com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
            at
com.android.okhttp.internal.http.HttpConnection$ChunkedSink.write(HttpConnection.java:330)
            at
com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at
com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
            at
com.alexbbb.uploadservice.UploadService.uploadFiles(UploadService.java:298)
            at
com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:169)
            at
com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:139)
            at
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)


On Thu, Mar 12, 2015 at 4:13 PM, idanbar134 <bar.idan@gmail.com> wrote:

> Hey )
>
> Thanks. i fixed it) have great day bro
>
>
> On Thu, Mar 12, 2015 at 8:51 AM, foodyi <notifications@github.com> wrote:
>
>> I just import java source code to my project,it works well.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/alexbbb/android-upload-service/issues/22#issuecomment-78431950>
>> .
>>
>
>
>
> --
> Idan Ayalon
>
>


-- 
Idan Ayalon

**Comment by venvear** [comment]
Hello Alex,
I'm trying to upload file to my server and i get an exception:

Error in upload with ID: 7a31894d-342e-4bfc-99be-4bbf4c0ae0c8. sendto failed: EPIPE (Broken pipe): java.net.SocketException: sendto failed: EPIPE (Broken pipe)
            at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
            at libcore.io.IoBridge.sendto(IoBridge.java:515)
            at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
            at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
            at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
            at com.android.okio.Okio$1.write(Okio.java:70)
            at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
            at com.android.okhttp.internal.http.HttpConnection$ChunkedSink.write(HttpConnection.java:334)
            at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
            at com.alexbbb.uploadservice.UploadService.uploadFiles(UploadService.java:290)
            at com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:163)
            at com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:133)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by idanbar134** [comment]
Hey Alex,
The problem solved thank

**Comment by alexbbb** [comment]
@venvear and @idanbar134 please open a new issue if you experience a problem rather than posting in existing issues like this, which has nothing in common with your problem and only adds confusion :) Thank you!

**Comment by aliceresponde** [comment]
@alexbbb  hi, I'm lost... 
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2    I clean, build  but  the  issue  continue.

**Comment by alexbbb** [comment]
Right now, to use Upload Service in Android Studio, I've simply imported the source code and the manifest in a new Android library project. I'm considering to migrate the library in android studio and publish it to jCentral. Please check issue #10. I'm closing this issue as the answer given by @foodyi works also for me.

@aliceresponde I'm using a Mac also, and I think your problem has to do with your java system settings.
