### ISSUE TITLE
Chat application porblem

### ISSUE THREAD

**Issue by idanbar134** [alexbbb/android-upload-service#24]
Hello,

when i upload an picture with the android-upload-service from the room everything works great.
if i get out from the room and come back i get this message 

        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:871)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
            at com.nuro.messaging.ChatFragment.sendMessage(ChatFragment.java:479)
            at com.nuro.messaging.ChatFragment.access$500(ChatFragment.java:63)
            at com.nuro.messaging.ChatFragment$11.onCompleted(ChatFragment.java:648)
            at com.alexbbb.uploadservice.AbstractUploadServiceReceiver.onReceive(AbstractUploadServiceReceiver.java:38)
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:861)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)

its happens to me only when i try to upload another file, but if i send text it works fine.
maybe it related to the service? 
if you need extra information you need to know tell me please.

Best
Idan

**Comment by alexbbb** [comment]
As the exception says:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
        at com.nuro.messaging.ChatFragment.sendMessage(ChatFragment.java:479)
```
You're invoking a method on a null object in your custom implementation of AbstractUploadServiceReceiver's onReceive method. Debug your code.

**Comment by idanbar134** [comment]
Hi Alex,

Thank, i'm noob programmer :) working on my skills. but thank you for best
support.

Idan

On Mon, Mar 9, 2015 at 3:36 PM, Alex Gotev <notifications@github.com> wrote:

> As the exception says:
>
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
>         at com.nuro.messaging.ChatFragment.sendMessage(ChatFragment.java:479)
>
> You're invoking a method on a null object in your custom implementation of
> AbstractUploadServiceReceiver's onReceive method. Debug your code.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alexbbb/android-upload-service/issues/24#issuecomment-77853841>
> .
>



-- 
Idan Ayalon

**Comment by alexbbb** [comment]
@idanbar134 keep working like you do :) I suggest you to learn how to read Java Stack Trace, as it's your "best friend" to find out what's going wrong in some cases. Sorry to bother you with this ticket you opened: https://github.com/alexbbb/android-upload-service/issues/22 again, but I need to know if you still have the described problem or how you managed to solve it :)

**Comment by idanbar134** [comment]
Thanks. I learn the hard way :) and I solved it.

**Comment by idanbar134** [comment]
Hi Alex,

I'm trying to upload a photo that i pick from the gallery using this code:

 public String getPath(Uri uri) {
        // just some safety built in
        if( uri == null ) {
            return null;
        }
        // try to retrieve the image from the media store first
        // this will only work for images selected from gallery
        String[] projection = { MediaStore.Images.Media.DATA };
        Cursor cursor = getActivity().getContentResolver().query(uri,
projection, null, null, null);
        if( cursor != null ){
            int column_index =
cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
            cursor.moveToFirst();
            return cursor.getString(column_index);
        }
        // this is our fallback here
        return uri.getPath();
    }


    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent
data) {
        super.onActivityResult(requestCode, resultCode, data);
        String realPath = "";

        if (resultCode == Activity.RESULT_OK  ) {
            if( requestCode == REQUEST_CAPTURE_PICTURE ){
                file = new
File(Environment.getExternalStorageDirectory().toString());
                for (File temp : file.listFiles()) {
                    if (temp.getName().equals("temp.jpg")) {
                        file = temp;

                       realPath = file.toString();
                        break;
                    }
                }
            }

            if (requestCode ==  REQUEST_PICK_PICTURE) {
                if (data != null ) {
                    selectedImageURI = data.getData();
                    Log.i(TAG, selectedImageURI.toString());

                    //realPath =
"/storage/emulated/legacy/20150308_184443.jpg";


                    realPath = getPath(selectedImageURI);

                }
            }

            // upload the files with android-upload-service
            UploadFileToServer(realPath, getActivity());
        }
    }

and this is my chooseImage method:

    private void chooseImage() {
        Intent intent = new Intent();
        intent.setType("image/*");
        intent.setAction(Intent.ACTION_GET_CONTENT);
        startActivityForResult(Intent.createChooser(intent, "Select
Picture"), REQUEST_PICK_PICTURE);
    }


the 'getPath' returns empty string and the app crashes...
i tried to direct 'realPath' (String) to real photo on SD and it worked.

i would be happy to know what is my noob mistake this time :)

best,

Idan



On Mon, Mar 9, 2015 at 4:57 PM, idanbar134 <bar.idan@gmail.com> wrote:

> Thanks. I learn the hard way :) and I solved it.
> On Mar 9, 2015 4:54 PM, "Alex Gotev" <notifications@github.com> wrote:
>
>> @idanbar134 <https://github.com/idanbar134> keep working like you do :)
>> I suggest you to learn how to read Java Stack Trace, as it's your "best
>> friend" to find out what's going wrong in some cases. Sorry to bother you
>> with this ticket you opened: #22
>> <https://github.com/alexbbb/android-upload-service/issues/22> again, but
>> I need to know if you still have the described problem or how you managed
>> to solve it :)
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/alexbbb/android-upload-service/issues/24#issuecomment-77868167>
>> .
>>
>


-- 
Idan Ayalon
