### ISSUE TITLE
POST parameters are not received from the server.

### ISSUE THREAD

**Issue by JanithaR** [alexbbb/android-upload-service#25]
I have used this library for various projects for a long time. Today I started running into a problem where none of the parameters sent via POST is not received by the server. They are simply missing at server end. I use a class with my own coding to make POST requests which do not have files and they work fine. Only requests made using this library fail with no POST parameters.

EDIT : I must note here that this was one specific server that was having the problem. The iOS version of the same app was successfully making successful POST requests as well.

**Comment by idanbar134** [comment]
Hi,

I solved the problem. it was wrong routing on the server side :)
thanks



On Thu, Mar 19, 2015 at 7:46 AM, JanithaR <notifications@github.com> wrote:

> I have used this library for various projects for a long time. Today I
> started running into a problem where none of the parameters sent via POST
> is not received by the server. They are simply missing at server end. I use
> a class with my own coding to make POST requests which do not have files
> and they work fine. Only requests made using this library fail with no POST
> parameters.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alexbbb/android-upload-service/issues/25>.
>



-- 
Idan Ayalon

**Comment by JanithaR** [comment]
Yes, I think that's the case here as well (I mean it's definitely server side issue). I've been with this problem for a few hours now. Could you elaborate what exactly you mean by "wrong routing on the server side"? I'm not a server guy or PHP but I need to wrap my head around this.

**Comment by nitinhayaran** [comment]
Have you figured out what was causing the issue. I am experiencing same issue, where I am getting custom headers on the server, but no POST or FILES.

**Comment by JanithaR** [comment]
Not yet. Still looking for it by the server side guys. I'll definitely
update here when I resolve the issue.

So far I could only narrow it down to the HttpURLConnection class. Because
when that's in use only it seems the sever is acting weird.

**Comment by alexbbb** [comment]
Have you tried using one of the example server implementations? 
https://github.com/alexbbb/android-upload-service/tree/master/examples

I don't know what your server architecture is, or if the traffic passes through a proxy before being handled by the server, but never had such an issue and I use the library in production with PHP and Python Twisted servers.

**Comment by JanithaR** [comment]
The server side is done using CodeIgniter and the same code base works on
the test servers and every other local server we tried. It's only this
particular client provided server having this issue.

On Wed, Mar 25, 2015 at 5:26 PM, Alex Gotev <notifications@github.com>
wrote:

> Have you tried using one of the example server implementations?
> https://github.com/alexbbb/android-upload-service/tree/master/examples
>
> I don't know what your server architecture is, or if the traffic passes
> through a proxy before being handled by the server, but never had such an
> issue and I use the library in production with PHP and Python Twisted
> servers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexbbb/android-upload-service/issues/25#issuecomment-85998359>
> .
>



-- 
grapixsoft@gmail.com

**Comment by alexbbb** [comment]
@JanithaR have you solved the issue?

**Comment by JanithaR** [comment]
Hey thanks for the bump, I seriously forgot to update here.

Yes one of the guys was able to figure it out. Here's his exact description.

The server doesn’t accept requests sent with the header
‘Transfer-Encoding’ = ‘chunk’.
I’ve tried to fix this on the VPS, but couldn’t find a reliable way to do it.
But you can turn it off in the Android code.
On UploadService.java, around line 270, remove the line
conn.setChunkedStreamingMode(0);


I tried it and it works just fine. I didn't have much time to go in depth
with this but for anyone running into the problem just make a copy of the
library, include that in your project and just comment the line specified
above.

Thanks

On Tue, Mar 31, 2015 at 7:46 PM, Alex Gotev <notifications@github.com>
wrote:

> @JanithaR <https://github.com/JanithaR> have you solved the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexbbb/android-upload-service/issues/25#issuecomment-88103864>
> .
>



-- 
grapixsoft@gmail.com

**Comment by alexbbb** [comment]
I seriously discourage removing
```
conn.setChunkedStreamingMode(0);
```
as it will cause errors when you try to upload big files. Here is the official Android documentation about the method: http://developer.android.com/reference/java/net/HttpURLConnection.html#setChunkedStreamingMode%28int%29

Even if we are in 2015 now, it's incredible how hard it may get to properly configure such an obvious thing as file upload, because it has to be finely configured both client side and server side. I suggest you to check your VPS server configuration or to remark the lack of this feature to your provider, as it's important.

**Comment by JanithaR** [comment]
Yes, I'm quite aware of that and I wouldn't recommend this either. Making a
copy of the library and commenting it out should be THE very last resort.

Since a lot of things aren't exactly under my control I had to resort to
just commenting it out. Plus I'm 99% confident the app won't upload files
larger than 1MB.

**Comment by JanithaR** [comment]
Hello there,

I just signed the petition "Facebook: Save Wilpattu One Srilanka's Most
Loved Place" and wanted to see if you could help by adding your name.

Our goal is to reach 15,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/8YghxxYjS8

Thanks!
Janitha
