### ISSUE TITLE
Cannot upload multiple files

### ISSUE THREAD

**Issue by Bryanearl** [alexbbb/android-upload-service#26]
When i add several files to upload, it only uploads the last file added to the arrayList

**Comment by idanbar134** [comment]
hey,

you can close this issue. thanks

On Mon, Mar 30, 2015 at 1:12 PM, Bryanearl <notifications@github.com> wrote:

> When i add several files to upload, it only uploads the last file added to
> the arrayList
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/alexbbb/android-upload-service/issues/26>.
>



-- 
Idan Ayalon
