### ISSUE TITLE
EPIPE (Broken pipe): exception in UploadService.uploadFiles(UploadService.java:290)

### ISSUE THREAD

**Issue by venvear** [alexbbb/android-upload-service#27]
Hello Alex,
I'm trying to upload file to my server and i get an exception:

Error in upload with ID: 7a31894d-342e-4bfc-99be-4bbf4c0ae0c8. sendto failed: EPIPE (Broken pipe): java.net.SocketException: sendto failed: EPIPE (Broken pipe)
at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
at libcore.io.IoBridge.sendto(IoBridge.java:515)
at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
at com.android.okio.Okio$1.write(Okio.java:70)
at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
at com.android.okhttp.internal.http.HttpConnection$ChunkedSink.write(HttpConnection.java:334)
at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
at com.alexbbb.uploadservice.UploadService.uploadFiles(UploadService.java:290)
at com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:163)
at com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:133)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by alexbbb** [comment]
Just to make sure that your configuration is correct:
- check if you have added all the required permissions to your AndroidManifest.xml (EPIPE happens often as a result of missing permissions)
- check that you are using the latest version of android-upload-service (open a terminal, navigate to the folder where you have cloned the git repo and execute: git pull)
- check that the URL on which you are making the http/multipart request is reachable

After that, please try an upload again and let me know if you have solved the problem

**Comment by Android33** [comment]
I am having issues in using this library. it gives me error on some files (http://prntscr.com/72e68t screenshot) broken pipe. (http://prntscr.com/72e7pu) it runs for others perfectly

**Comment by Android33** [comment]
http://prntscr.com/72ey4c now the problem is at line 172

**Comment by alexbbb** [comment]
@Android33 can you provide a test case and tell me which web server are you using?

**Comment by alexbbb** [comment]
I've experienced this problem while trying to upload large files which exceeds maximum POST data length set on server. The multipart header that Android Upload Service sends does not specify a "Content-Length", so the server could not validate and refuse the request in advance. What happens is that at some point, when the maximum post data is reached, the server closes the stream, and the "Broken pipe" arises on the client side. This is the same behavior described in RFC 1867 on paragraph 5.2: https://www.ietf.org/rfc/rfc1867.txt

To try to solve this issue, I made this commit: https://github.com/alexbbb/android-upload-service/commit/50a83a361c1e0ab8bfac4c976c9fdaf36b925e43 which adds the total content length of the request in the headers. I encourage everyone who uses the library to update to the latest commit, make some tests and report any errors here.

**Comment by alexbbb** [comment]
The current master at the time of this writing: https://github.com/alexbbb/android-upload-service/commit/b65b6ccc7ac8d5a708b53c79f0af5e27202001cc works for me after the modifications, in all the test cases using PHP server and node.js server backends

**Comment by agrawalamod** [comment]
For some reason, I still keep getting this error. I am using the latest commit (3.0) for the library with Node JS server. This is specifically for large files that exceed maximum POST data length set on server.

**Comment by gotev** [comment]
Can you replicate the error with the demo server provided in the examples?

**Comment by agrawalamod** [comment]
Yes, I am using the Node JS server from examples. It works perfectly fine for smaller files (<1 GB). I was using this service for a long time and never faced this issue before. Lately, this is an issue (since 2.1, I think).

**Comment by gotev** [comment]
Ok, so to be able to replicate the issue, I also need the debug log from the library (check in the wiki > Recipes) and the output from the server when the error arises. Thank you.

**Comment by agrawalamod** [comment]
Sure. I have enabled debugger. I have attached the output for Android logcat and Node JS server. There's no error on server, it is just left hanging. Server does show content-length from the header. This happens when I try to upload >2 GB of data (using multiple multipart requests in parallel or single multipart request). 
[Android output](https://gist.github.com/agrawalamod/33bd711009b4bf32aae4c1806829bb2d)
[Server output](https://gist.github.com/agrawalamod/9944e1680ecc2f47b61a45861e87ef65)

**Comment by gotev** [comment]
From what I see, it could be a server-side issue. Currently the node.js demo server uses multer 0.1.8. I've seen that currently 1.x is available. The first step is to upgrade multer to the latest version. Its public API has changed so some refactorings will be needed, too.
