### ISSUE TITLE
how to upload multiple files？

### ISSUE THREAD

**Issue by 2639117470** [alexbbb/android-upload-service#28]
Hi，Alex，how to upload multiple files？
i try to do it like this，but failed。

UploadRequest request = new UploadRequest(this, UUID.randomUUID().toString(), erverUrlString);
request.addFileToUpload(fileToUploadPath_1, paramNameString, "1.jpg",
		        ContentType.APPLICATION_OCTET_STREAM);
request.addFileToUpload(fileToUploadPath_2, paramNameString, "2.jpg",
		        ContentType.APPLICATION_OCTET_STREAM);
UploadService.startUpload(request);

the code just uploaded “1.jpg”，have not upload "2.jpg"。

**Comment by ravenet** [comment]
Hi,

Please check you server are u receiving all files or only file. I am sure it is sending multiple files and i was send more than 10 images and it sent nicely.

Thanks

**Comment by shaneharris** [comment]
It sends all the files under one parameter in one request. Check your 'paramNameString' parameter has the array notation i.e. 

```Java
String paramNameString = "theparameter[]";
```

and not...

```Java
String paramNameString = "theparameter";
```
Remember you will have to handle this differently on the server. 

Another option is to use a different 'paramNameString' parameter for each file.

**Comment by shoebhoney** [comment]
Hi，Alex，I am getting an Error, Could not parse multipart and server code 500
i am sending two files with different params names.

UploadRequest request = new UploadRequest(this, UUID.randomUUID().toString(), erverUrlString);
request.addFileToUpload(fileToUploadPath_1, paramNameString1, "1.jpg",
ContentType.APPLICATION_OCTET_STREAM);
request.addFileToUpload(fileToUploadPath_2, paramNameString2, "2.jpg",
ContentType.APPLICATION_OCTET_STREAM);
UploadService.startUpload(request);

**Comment by alexbbb** [comment]
500 Internal Server Error means that there's something wrong on the server
side. Please check your server code and also try one of the server examples
I provided with the library.
Il 14/lug/2015 05:50 AM, "shoebhoney" <notifications@github.com> ha scritto:

**Comment by shoebhoney** [comment]
Thanks Alex, 
I will check
My another issue is with progress bar, it fills 100% but file still uploading.
What i have to do for this?

**Comment by alexbbb** [comment]
@shoebhoney Never experienced such issue with the progress bar. Do you have the same problem even after you have solved you server-side issues?
