### ISSUE TITLE
Upload file on Akamai Server

### ISSUE THREAD

**Issue by alphamu** [alexbbb/android-upload-service#31]
Uploads to Akami servers fail.

From what I was told, this was because not `Content-Length` was being passed in the headers.
After a lot of debugging, turns out `conn.setChunkedStreamingMode(0)` is the issue. Setting the chucked mode sends by default data is 1024 bytes and it sends headers with each bit of data. I would recommend removing this option.

**Comment by alexbbb** [comment]
Akamai servers does not support HTTP/1.1?
Disabling chunked mode can cause serious issues when uploading big files.

Please check this:
http://developer.android.com/reference/java/net/HttpURLConnection.html#setChunkedStreamingMode%28int%29

Do you have any suggestions?

**Comment by alphamu** [comment]
I found some php posts suggesting that this was the problem. From what I could tell, the problem may either be chunkedmode or something to do with content-length. We ran a lot of tests trying to set content length on each chunk with no luck. From what i understand, Akami expects content-length with each chunk. I do know the problem did not occur in UAT but came up in production. The main difference between the 2 environments was Akami.

**Comment by alexbbb** [comment]
@alphamu Do you know if there is a documentation from akamai, explaining how they expect the multipart form upload? It would be useful to improve the library and make it work seamlessly with akamai servers

**Comment by alexbbb** [comment]
Maybe the problem could be solved by setting the global "Content-Length" header (parameters + files)  in the root of the Multipart HTTP request before starting the upload.
I've seen that nginx complains if that header is not present, and that could be also your case.

**Comment by alphamu** [comment]
We did try to test that, don't think it worked, though to be fair we were doing it by hand and its almost impossible to set the content-length by hand. 
I didn't find any documentation from Akamai, since the work was for a client, they didn't bother to help either, if you can tell me how to change the code for this, I can try this on their server and let you know if it worked, will take a day or so though since I'm busy with something else today.

**Comment by alexbbb** [comment]
@alphamu Committed some changes to try to solve this issue. I haven't had time to test it, so please update the library in your projects and let me know if it works in your development and production scenarios. Thank you :)

**Comment by alphamu** [comment]
@alexbbb sorry but seems that at some point you used URI and have since switched to using String paths. I had to go through and change the code to accomodate for this, the problem is that my changes don't seem to work and I got the error below. This could be becausing simply doing uri.toString isn't enough or it could be one of the few other changes I had to make, don't really have time to investigate this at the moment, will see if I can do it over the weekend.

E/TrueLocal(16521): java.io.FileNotFoundException: /content:/media/external/images/media/73: open failed: ENOENT (No such file or directory)
E/TrueLocal(16521): 	at libcore.io.IoBridge.open(IoBridge.java:409)
E/TrueLocal(16521): 	at java.io.FileInputStream.<init>(FileInputStream.java:78)
E/TrueLocal(16521): 	at com.alexbbb.uploadservice.FileToUpload.getStream(FileToUpload.java:48)
E/TrueLocal(16521): 	at com.alexbbb.uploadservice.UploadService.uploadFiles(UploadService.java:314)
E/TrueLocal(16521): 	at com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:175)
E/TrueLocal(16521): 	at com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:139)
E/TrueLocal(16521): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/TrueLocal(16521): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/TrueLocal(16521): 	at android.os.Looper.loop(Looper.java:137)
E/TrueLocal(16521): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/TrueLocal(16521): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
E/TrueLocal(16521): 	at libcore.io.Posix.open(Native Method)
E/TrueLocal(16521): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
E/TrueLocal(16521): 	at libcore.io.IoBridge.open(IoBridge.java:393)
E/TrueLocal(16521): 	... 9 more
E/TrueLocal(16521): [CreateTagService:onError] - uploadTagImage.onError called /content:/media/external/images/media/73: open failed: ENOENT (No such file or directory)

**Comment by alexbbb** [comment]
@alphamu Checked you exception stack trace. The error you described has nothing to do with the recent changes I've made. The library internally has always used string paths. You have to specify the full absolute paths to the files you want to upload. From what I see, I think you have provided a wrong file path in the "addFileToUpload" method, resulting in the "FileNotFoundException". Please check the paths you provide. This doesn't seem to be an issue with the library.

**Comment by alphamu** [comment]
The file was selected from the Android gallery/photos app, the path is
correct for an internal uri though the leading / indicates you want a full
path which I'm not sure I can get. I recall there was a way, buy I'll need
time to investigate it.

**Comment by alexbbb** [comment]
@alphamu Try this way to obtain an absolute path from an URI:
```java
String absolutePath = new File(uri).getCanonicalPath()
```

**Comment by alphamu** [comment]
I used different code, but I verified in the debugger the path was correct.
It seems to upload now and doesn't output any errors, but I'm still getting a 504 timeout.
Same code with chunked mode removed works.

It does seem to upload to 100% with chunked mode on, but then something goes wrong, take a look at the similarity and difference in the log output. Note, the second one is kinda long.
https://www.dropbox.com/s/roj2pkb8krxzlar/upload_log.txt?dl=0

**Comment by alphamu** [comment]
This is the gist from Charles Proxy (which in hindsight was probably a mistake to put up).
https://gist.github.com/anonymous/c18c68ca52ada39a5b15

**Comment by alexbbb** [comment]
@alphamu I've seen the logs. I suggest you to filter logcat output to only get your app log messages.
Made some other modifications. Please update the library sources, try again and let me know :)

**Comment by alphamu** [comment]
Only have access to the source from work, will have to wait till Monday.
If you know how to file from the command line, do share, every command I've
come across doesn't seem to work.

**Comment by alexbbb** [comment]
@alphamu Any news?

**Comment by alphamu** [comment]
Sorry Alex, got busy.
Will try to test it out soon.

On Tue, Aug 18, 2015 at 7:36 PM, Alex Gotev <notifications@github.com>
wrote:

> @alphamu <https://github.com/alphamu> Any news?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexbbb/android-upload-service/issues/31#issuecomment-132143534>
> .
>



-- 
"If the world should blow itself up, the last audible voice would be that
of an expert saying it can't be done." --Peter Ustinov

**Comment by alphamu** [comment]
Hey Alex,

Good news, whatever the last change was, it seems to have fixed it!
Just be warned that they could have changed something on the server side in all this time but my image uploads are succeeding! Good job! I think you may be the first library who can claim to work with Akamai!

**Comment by alexbbb** [comment]
Thank you for testing and I'm glad that it's working! In the library I've
definitely switched from chunked mode to fixed size mode, so the server
knows in advance the total upload length.
Il 19/ago/2015 04:58 AM, "Ali Muzaffar" <notifications@github.com> ha
scritto:
