### ISSUE TITLE
How to pass ByteArrayBody?

### ISSUE THREAD

**Issue by shoebhoney** [alexbbb/android-upload-service#33]
Hello Alex,

I am uploading a Video to server as file, my need is to upload the thumbnail image of that video. So how can i do this in your library.
My server end developer need ByteArrayBody, so please tell me how to pass ByteArrayBody?

**Comment by alexbbb** [comment]
Save the ByteArray to a file on the device, then add the full path to the
file to the request.

2015-07-14 9:43 GMT+02:00 shoebhoney <notifications@github.com>:

**Comment by shoebhoney** [comment]
That's Grt! work for me.
Thank you Alex.

**Comment by alexbbb** [comment]
;)
