### ISSUE TITLE
JitPack.io build failure

### ISSUE THREAD

**Issue by martofeld** [alexbbb/android-upload-service#34]
Hey, i wanted to use the library but your build is failing on jitpack
Log https://jitpack.io/com/github/alexbbb/android-upload-service/1.1/build.log

**Comment by alexbbb** [comment]
From my tests, by using the latest commit available today: https://jitpack.io/#alexbbb/android-upload-service/9d589d2df4
the problem is not arising anymore, after the changes I've made to the gradle build file.
