### ISSUE TITLE
Unlimited retries

### ISSUE THREAD

**Issue by lefkatis** [alexbbb/android-upload-service#35]
Can I choose to make the service retry until it sends the data successfully?
Does it provide listeners for connectivity so as it would try to send the request when internet is available?

**Comment by alexbbb** [comment]
At the moment, you can set a high retry value (e.g. 100). If you want to
retry when internet is available, is up to you to implement it to suit your
needs. Usually this is done by implementing a broadcast listener which
listens to internet connectivity change (check official Android docs).
Then, in the listener implementation, you can start the upload as shown in
the examples.
Il 05/ago/2015 11:57 PM, "lefkatis" <notifications@github.com> ha scritto:
