### ISSUE TITLE
The possiibility to upload several multipart files

### ISSUE THREAD

**Issue by salgado** [alexbbb/android-upload-service#39]

**Comment by alexbbb** [comment]
Do you mean the possibility to upload several files in a single upload
request?
Il 19/ago/2015 05:43 AM, "Alex Salgado" <notifications@github.com> ha
scritto:

**Comment by salgado** [comment]
Not necessary in na single request but in a single action. E.g. I have 100
video files 7MB each, to send on a click button with progress bar.
Em 19/08/2015 02:01, "Alex Gotev" <notifications@github.com> escreveu:

**Comment by alexbbb** [comment]
To upload multiple files in a single request, check the provided example: https://github.com/alexbbb/android-upload-service#how-to-start-android-upload-service-to-upload-files

and simply make N calls to request.addFileToUpload for each one of the files you want to add to the upload request.

Once you start the upload, you will see the overall upload progress in the notification.

**Comment by salgado** [comment]
Hi Alex,

I tried this but the memory is going full because, as you said, it build
the files to send in a single request.
Is it possible to send multiples request ?

Can you see my initial code here ?
https://github.com/igarape/copcast-android/blob/upload-service-intent/app/src/main/java/org/igarape/copcast/views/UploadVideoActivity.java

Thanks
Alex

2015-08-19 8:14 GMT-03:00 Alex Gotev <notifications@github.com>:

**Comment by alexbbb** [comment]
From what I see in your code, I suggest you to try to make N upload requests, one for each one of the video files you want to upload:
```java
while (!videos.isEmpty() && cont<=numVideos) {
    UploadRequest request = new UploadRequest(this, UUID.randomUUID().toString(), serverUrlString);
    
    //setup the request and add the video file
    
    try {
        UploadService.startUpload(request);
    } catch (Exception exc) {
        Toast.makeText(this, "Malformed upload request. " + exc.getLocalizedMessage(), Toast.LENGTH_SHORT).show();
    }
}
```

**Comment by salgado** [comment]
Thanks, I will try it.
I forgot to send you the error before:
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ at
com.alexbbb.uploadservice.UploadService.uploadFiles(UploadService.java:381)
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ at
com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:234)
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ at
com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:165)
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ at
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ at
android.os.Handler.dispatchMessage(Handler.java:102)
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ at
android.os.Looper.loop(Looper.java:146)
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ at
android.os.HandlerThread.run(HandlerThread.java:61)
08-21 09:51:47.502    8041-9093/org.igarape.copcast I/dalvikvm﹕ [ 08-21
09:51:47.512  8041: 9093 W/dalvikvm ]
    threadid=13: thread exiting with uncaught exception (group=0x41f59da0)
08-21 09:51:50.765    8041-9093/org.igarape.copcast E/AndroidRuntime﹕ FATAL
EXCEPTION: IntentService[com.alexbbb.uploadservice.UploadService]
    Process: org.igarape.copcast, PID: 8041
    java.lang.OutOfMemoryError
            at
java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
            at
java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
            at java.lang.StringBuffer.append(StringBuffer.java:219)
            at
com.splunk.mint.network.io.OutputStreamMonitor.updateBody(OutputStreamMonitor.java:67)
            at
com.splunk.mint.network.io.OutputStreamMonitor.write(OutputStreamMonitor.java:58)
            at
java.io.BufferedOutputStream.write(BufferedOutputStream.java:131)
            at
com.android.okhttp.internal.http.HttpTransport$FixedLengthOutputStream.write(HttpTransport.java:236)
            at
com.alexbbb.uploadservice.UploadService.uploadFiles(UploadService.java:381)
            at
com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:234)
            at
com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:165)
            at
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.os.HandlerThread.run(HandlerThread.java:61)
08-21 09:51:50.825    8041-8041/org.igarape.copcast I/UploadVideoActivity﹕
onPause
08-21 09:51:56.231    8041-9093/org.igarape.copcast I/Process﹕ Sending
signal. PID: 8041 SIG: 9

2015-08-21 10:58 GMT-03:00 Alex Gotev <notifications@github.com>:

**Comment by patelanil2007** [comment]
how to upload multiple file parallel??

**Comment by alexbbb** [comment]
@patelanil2007 
you can't, the upload service handles only one upload request at a time
