### ISSUE TITLE
Manifest merger failed when gradle build

### ISSUE THREAD

**Issue by jk2K** [alexbbb/android-upload-service#41]
I add `compile 'com.github.alexbbb:android-upload-service:1.3'` to my project dependencies

it throws gradle build error
```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/HelloTheme) from AndroidManifest.xml:12:9-42
  	is also present at [com.github.alexbbb:android-upload-service:1.3] AndroidManifest.xml:17:9-40 value=(@style/AppTheme)
  	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:6:5-30:19 to override
```

What can i do?

**Comment by alexbbb** [comment]
Exactly what gradle suggest in the error log you sent to me.
Add
```
tools:replace="android:theme"
```
in your app manifest's application tag
Il 28/ago/2015 06:32 AM, "jk2K" <notifications@github.com> ha scritto:

**Comment by jk2K** [comment]
now it throws gradle build error
```
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

**Comment by alexbbb** [comment]
Googling around for this kind of problems is always useful :)
http://stackoverflow.com/questions/29756188/java-finished-with-non-zero-exit-value-2-android-gradle

**Comment by alexbbb** [comment]
Made a little change to the library manifest in the last commit, so you don't need to add the tools:replace directive in your app's manifest. You can try it out in your gradle build file:
```
dependencies {
    compile 'com.github.alexbbb:android-upload-service:51cfe3d32d'
}
```

**Comment by jk2K** [comment]
thanks,now  it is ok with using version 1.3.1
