### ISSUE TITLE
Gradle build Failure 

### ISSUE THREAD

**Issue by linkindrew** [alexbbb/android-upload-service#42]
i've added screen shots of build.gradle (Project) and build.gradle (Module : app ) . build fails when a add this dependency : 

	        compile 'com.github.alexbbb:android-upload-service:1.3'

and error is : 

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

![screen shot 2015-08-30 at 11 49 47 am](https://cloud.githubusercontent.com/assets/13833204/9566073/17f61120-4ec2-11e5-959e-47f8a91a1888.png)
![screen shot 2015-08-30 at 11 50 05 am](https://cloud.githubusercontent.com/assets/13833204/9566074/1e576f96-4ec2-11e5-9757-877e84d40f98.png)

**Comment by alexbbb** [comment]
Check #41

**Comment by linkindrew** [comment]
dependencies {
    compile 'com.github.alexbbb:android-upload-service:51cfe3d32d'
}

Eliminated the Gradle sync. error i mentioned above , now error is occuring on RUN : 

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

same i guess , i tried commenting 
   compile fileTree(dir: 'libs', include: ['*.jar'])
but nothing

**Comment by alexbbb** [comment]
Have you followed the setup instructions in the readme after that you've
set the gradle dependency?
Il 30/ago/2015 09:21 AM, "linkindrew" <notifications@github.com> ha scritto:

**Comment by linkindrew** [comment]
yup , i have setup manifest according to instructions . here is result 
![screen shot 2015-08-30 at 1 18 42 pm](https://cloud.githubusercontent.com/assets/13833204/9566295/7ad97136-4ece-11e5-9ba0-060ece6987c4.png)
:

![screen shot 2015-08-30 at 1 18 16 pm](https://cloud.githubusercontent.com/assets/13833204/9566294/708668d8-4ece-11e5-97b5-3080b0cc73a5.png)

**Comment by linkindrew** [comment]
note that "tools:replace="android:theme" had no effect , and  removing "android:exported=false" from service tag eliminated 2nd error , but old error comes back

**Comment by alexbbb** [comment]
There was an error in the demo application's gradle build file. 
Made a commit to fix it: https://github.com/alexbbb/android-upload-service/commit/247ce33bfb5399d80eb253128c36ca131b769e4f
Please update your local source files to the latest commit and try again

**Comment by linkindrew** [comment]
no success ... successful gradle sync. but failure in execution : 

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by linkindrew** [comment]
please notice my "compileSDKVersion" and "buildToolsVersion" in gradle.build image above , could they be causing this ? should i change those too ?

**Comment by alexbbb** [comment]
I seem to have found what caused the issue! When you include different versions of some dependency libraries (in this case android-support-v4.jar) it fails to run. Made another commit: https://github.com/alexbbb/android-upload-service/commit/e257d727bb0a46cc7487c0c2534a7ee9138bd950
Please update your sources and retry :)

**Comment by linkindrew** [comment]
finally , perfect . Thanks alot for special effort. you are the man :) :) p.s sent you friend req. on fb m w'd be my pleasure if u accept :)

**Comment by alexbbb** [comment]
Thank you, too :+1: 
Made the minor release 1.3.1: https://github.com/alexbbb/android-upload-service/releases
