### ISSUE TITLE
serverResponseMessage  ignores newline

### ISSUE THREAD

**Issue by jk2K** [alexbbb/android-upload-service#46]
android studio logcat show
![image](https://cloud.githubusercontent.com/assets/4025839/9713506/6651ba9a-5584-11e5-9389-23da09388ed0.png)

the link is wrong, no post suffix

The corrent result should be
![image](https://cloud.githubusercontent.com/assets/4025839/9713537/98e4800a-5584-11e5-843c-f9f0009a67cc.png)

**Comment by alexbbb** [comment]
The server response string that you get in the broadcast receiver is generated by this method: https://github.com/alexbbb/android-upload-service/blob/master/src/com/alexbbb/uploadservice/HttpUploadTask.java#L212
Made a little modification and now it should add new lines received from server. Please give it a try :)
https://jitpack.io/#alexbbb/android-upload-service/d4a7a3baaf

**Comment by jk2K** [comment]
thanks a lot
