### ISSUE TITLE
Update examples & docs

### ISSUE THREAD

**Issue by alexbbb** [alexbbb/android-upload-service#49]
Update example app project by adding:
- option to enable and disable ringtone for the upload task
- binary file upload capability

Add server-side demo implementations which supports binary file upload.
Update README.md examples for multipart upload and binary upload.

**Comment by PanayotCankov** [comment]
I plan to send these #50 but I am still polishing some stuff on my side (JavaScript mostly). When do you plan to release 1.4?

**Comment by alexbbb** [comment]
@PanayotCankov there's no release schedule, my policy is to release a new version when it's stable and well documented
