### ISSUE TITLE
Binary upload documentation

### ISSUE THREAD

**Issue by PanayotCankov** [alexbbb/android-upload-service#50]
There is a plugin for NativeScript using the binary upload live here:
https://www.npmjs.com/package/nativescript-background-http
There is a nodejs server used for its automation tests here:
https://github.com/NativeScript/nativescript-background-http/blob/master/examples/www/server.js
There is no Java example there since its used from bindings to JavaScript in the plugin.

 - [ ] Update the README.md with and example for a single file binary upload
 - [ ] Add a simple nodejs server example (simpler than the server for the automation tests)
 - [x] Consider adding the [nativescript-background-http](https://www.npmjs.com/package/nativescript-background-http) in the used by section

(I will send you a pull request in about 10 days with these)

**Comment by alexbbb** [comment]
@PanayotCankov I'll take care of README.md update with binary upload example and a link to nativescript-background-http
