### ISSUE TITLE
multi thread uploading

### ISSUE THREAD

**Issue by chenUT** [alexbbb/android-upload-service#52]
Do you have plan to support concurrent uploading in the near future? e.g using `threadPoolExecutor` or an array of threads( like the one done by volly) for a better performance?

**Comment by alexbbb** [comment]
It would be a nice addition to have. Dò you want to contribute by halping
implementing it?
Il 09/ott/2015 09:13 PM, "chenUT" <notifications@github.com> ha scritto:

**Comment by chenWork** [comment]
I would love to do so :). I will do a fork and create a another Service Class holds a `threadExecutePool`  which can perform uploads in parallel ?

**Comment by alexbbb** [comment]
Great! Feel free to fork the project and implement all the things you need
for multithreaded upload, then send me a pull request
Il 09/ott/2015 09:49 PM, "chenWork" <notifications@github.com> ha scritto:

**Comment by mabdurrahman** [comment]
I've forked the library and added the support for multiple uploads at once, it would be perfect to review the changed on this Pull request: https://github.com/alexbbb/android-upload-service/pull/69 and merge if possible...

**Comment by alexbbb** [comment]
feature added by merging pull request #69

**Comment by alexbbb** [comment]
2.0 with multi thread upload support is now released!
