### ISSUE TITLE
Issue with the gradle file

### ISSUE THREAD

**Issue by pushkarmoi** [alexbbb/android-upload-service#53]
The jitpack link provided for gradle file seems to be incorrect. Please check.
I'm using:

url "https://jitpack.io"
 compile 'com.github.alexbbb:android-upload-service:1.4'

**Comment by alexbbb** [comment]
Have you added this to your top-level gradle build file?
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
```
If it doesn't work, then clone the project to your computer, open the example app project and check if you are abel to build and run it.

**Comment by alexbbb** [comment]
The library has just been added to jcenter repository. Please check updated dependency instructions here: https://github.com/alexbbb/android-upload-service#setup
