### ISSUE TITLE
no multipart boundary content

### ISSUE THREAD

**Issue by kuronaru** [alexbbb/android-upload-service#55]
i was try to upload a file with `multipart-data` and i use Charles for debugging and the custom API i use says that the request i have doesn't have a multipart boundary content

**Comment by alexbbb** [comment]
Please post the code you use to create the request and a dump of the request from Charles

**Comment by kuronaru** [comment]
here's the code:

    private void upload() {

        File file = new File(Environment.getExternalStorageDirectory() + "/Download/sample.mp4");
        if (!file.exists()) {
            Toast.makeText(AlexbbbUploadActivity.this, "add file /Download/sample.mp4", Toast.LENGTH_SHORT).show();
        }

        final UploadRequest request = new UploadRequest(
                getApplicationContext(),
                "custom-upload-id",
                APIConstants.BASE_URL + APIConstants.UPLOAD_VIDEO
        );

    /*
     * parameter-name: is the name of the parameter that will contain file's data.
     * Pass "uploaded_file" if you're using the test PHP script
     *
     * custom-file-name.extension: is the file name seen by the server.
     * E.g. value of $_FILES["uploaded_file"]["name"] of the test PHP script
     */
        request.addFileToUpload(
                Environment.getExternalStorageDirectory() + "/Download/sample.mp4"/*"/absolute/path/to/your/file"*/,
                "file"/*"parameter-name"*/,
                null/*"custom-file-name.extension"*/,
                "multipart/form-data"/*"content-type"*/);

        //You can add your own custom headers
        request.addHeader("Authorization", "Bearer" + " " + PrefsUtils.getToken(getApplicationContext()));
        request.addHeader("Content-Type", "multipart/form-data");

        request.addParameter("fileName", "sample.mp4");
        request.addParameter("quizId", "1");

        //configure the notification
        request.setNotificationConfig(android.R.drawable.ic_menu_upload,
                "notification title",
                "upload in progress text",
                "upload completed successfully text",
                "upload error text",
                false);

        // set a custom user agent string for the upload request
        // if you comment the following line, the system default user-agent will be used
        request.setCustomUserAgent("UploadServiceDemo/1.0");

        // set the intent to perform when the user taps on the upload notification.
        // currently tested only with intents that launches an activity
        // if you comment this line, no action will be performed when the user taps on the notification
        request.setNotificationClickIntent(new Intent(getApplicationContext(), AlexbbbUploadActivity.class));

        // set the maximum number of automatic upload retries on error
        request.setMaxRetries(2);

        try {
            //Start upload service and display the notification
            UploadService.startUpload(request);

        } catch (Exception exc) {
            //You will end up here only if you pass an incomplete UploadRequest
            Log.e("AndroidUploadService", exc.getLocalizedMessage(), exc);
        }
    }


and here's the screenshot from Charles:

<img width="921" alt="screen shot 2015-11-12 at 11 32 49 am" src="https://cloud.githubusercontent.com/assets/5925092/11112112/dd79f26e-894a-11e5-9c1b-c8c39b6108b6.png">

**Comment by alexbbb** [comment]
This is strange. Your code seems correct to me, but you use the old upload API. Please do uploads like this: https://github.com/alexbbb/android-upload-service#http-multipart-upload-example 
What version of the library are you using? I've tried to replicate the problem you described, but with no luck. In my tests the boundary gets correctly passed in the `Content-Type` header.

I'll explain how I made my tests on OS X. I don't use proxy tools like Charles, 'cause I prefer the good old combination of tcpdump and wireshark to analyze what's happening on the network.

1. Open a terminal. Create a new folder somewhere in your local filesystem and enter into it: 
`mkdir test && cd test`

2. Checkout the latest library sources: 
`git clone https://github.com/alexbbb/android-upload-service`

3. navigate to `examples/server-nodejs` and then execute: 
`npm install; npm start` 
This will start the test HTTP Multipart server (you need node.js. If you don't have it, follow this guide: https://github.com/nodejs/node-v0.x-archive/wiki/installing-node.js-via-package-manager)

5. Open up another terminal and start a tcpdump on your network interface (in my case is called en0):
`cd && sudo tcpdump -i en0 -w test.pcap`

4. With Android Studio, open the example app (situated in `examples/app`), compile it and make it run on your android device

5. By using a file explorer tool like [ES File Explorer](https://play.google.com/store/apps/details?id=com.estrongs.android.pop), get the full path of a file on your device. In ES File Explorer this is done by selecting the file, then opening "properties" and then tapping on "copy full path".

6. Go back to Upload Service Demo App and fill in the fields as follows:
Server script URL: `http://YOUR_LOCAL_IP:3000/upload/multipart`
Path of the file to upload: `paste the URL got from ES File Explorer`
File parameter name: `test`
Then tap on `Multi-Part Upload`

7. If everything was setup correctly and you don't have any networking or firewalling issues between your android device and your computer, you will see the success upload notification, and the following output in the server console window:
  ```
Started multipart upload of: test
Finished multipart upload of: test to: uploads/test
  ```

8. Stop `tcpdump` by hitting CTRL+C and the open the pcap file in wireshark. You will see the following:
<img width="1440" alt="wireshark" src="https://cloud.githubusercontent.com/assets/2735858/11168079/114e19da-8b80-11e5-85c1-0c45dc1a3dc7.png">

Please make a test and let me know :)

**Comment by alexbbb** [comment]
@kuronaru any news?

**Comment by alexbbb** [comment]
Based on further testing with the latest release, the boundary gets always passed, so I've marked this as invalid and I'm closing the issue.
