### ISSUE TITLE
onNotificationClick Auto Cancel flag

### ISSUE THREAD

**Issue by dualcnhq** [alexbbb/android-upload-service#59]
Can we implment onNotificationClick
`notification.flags |= Notification.FLAG_AUTO_CANCEL;` 
or `Notification.Builder.setAutoCancel(true)`?

**Comment by alexbbb** [comment]
You want to make the notification to disappear automatically if the upload
has been completed without errors, or when the user taps on it?
Il 24/nov/2015 07:22 AM, "Clau Yagyagan" <notifications@github.com> ha
scritto:

**Comment by dualcnhq** [comment]
when the user taps on it coz it's still there whenever it's completed or when the user go back to the given intent

**Comment by alexbbb** [comment]
It's possible to add a configuration option to make the notification
disappear automatically when the upload has been completed and when the
user taps on it to open the associated intent.
Il 24/nov/2015 07:50 AM, "Clau Yagyagan" <notifications@github.com> ha
scritto:

**Comment by dualcnhq** [comment]
where can i add that?

**Comment by alexbbb** [comment]
Implemented the new feature! Update your project dependencies to use release 1.5:
```
dependencies {
    compile 'com.alexbbb:uploadservice:1.5'
}
```
then, when you configure the notification settings in your code, you can set the auto clear flag when the user taps on it
```java
//configure the notification
//the last two boolean parameters sets:
// - whether or not to auto clear the notification after a successful upload
// - whether or not to clear the notification after the user taps on it
request.setNotificationConfig(android.R.drawable.ic_menu_upload,
                              "notification title",
                              "upload in progress text",
                              "upload completed successfully text",
                              "upload error text",
                              false, true);
```
