### ISSUE TITLE
sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by kalyani30** [alexbbb/android-upload-service#6]
hello,
I implemented your library in my project and it works great for small pics...

but most of the time when i try to upload big images ,i am getting following exception
java.net.SocketException: sendto failed: EPIPE (Broken pipe)...

Or some times it's just displaying error notification...
can you please suggest me??

**Comment by SilvestreRamirez** [comment]
someone found a solution?

**Comment by gotev** [comment]
@SilvestreRamirez yes, check this: https://github.com/gotev/android-upload-service/wiki/Troubleshooting-Procedure#sockettimeout-or-broken-pipe-while-uploading
