### ISSUE TITLE
How to handle fail request

### ISSUE THREAD

**Issue by djhacktor** [alexbbb/android-upload-service#60]
Is there a pay to handle exception other than bad request in MultipartUploadRequest

**Comment by alexbbb** [comment]
You have two scenarios:
1. The request to the server is successful, but something wrong happens in
the server
2. The request to the server is not successful, and so you have something
that goes wrong on the client side.

Both scenarios are handled by using the BroadcastReceiver event handlers
(check README). You handle the first one by checking the server response
code in the onCompleted method, and the second one in the onError method,
where you get the Exception which caused the error.
Il 28/nov/2015 12:53 PM, "DjHacktor" <notifications@github.com> ha scritto:

**Comment by djhacktor** [comment]
'public void onError(String uploadId, Exception exception) 'does it handles all exception like file not found exception ?

**Comment by alexbbb** [comment]
Yes
Il 28/nov/2015 01:30 PM, "DjHacktor" <notifications@github.com> ha scritto:
