### ISSUE TITLE
Ability to disable to notification

### ISSUE THREAD

**Issue by Isaackingston** [alexbbb/android-upload-service#61]
Would love to have the ability to disable to notification for certain upload which will be done in background.

**Comment by alexbbb** [comment]
If you want to contribute by adding this feature, you can fork the project and then send me a pull request :)

**Comment by alexbbb** [comment]
This is a feature implemented in 1.6. Check [release notes](https://github.com/alexbbb/android-upload-service/releases/tag/1.6) and updated demo app.
