### ISSUE TITLE
Could not find method setFixedLengthStreamingMode.

### ISSUE THREAD

**Issue by Babar-Bashir** [alexbbb/android-upload-service#62]
Could not find method java.net.HttpURLConnection.setFixedLengthStreamingMode, referenced from method com.alexbbb.uploadservice.HttpUploadTask.upload

how to solve this issue

**Comment by alexbbb** [comment]
Please explain what you need to do and why you need to call that method

**Comment by Babar-Bashir** [comment]
I upload files to xampp local server but this exception occur

**Comment by Babar-Bashir** [comment]
I want to test upload Image file to local server Xampp but suggestion occur and file uploading error after 2-3 minute notification

**Comment by alexbbb** [comment]
@Babar-Bashir I can't help you with the information you provided. Please post the exception that occurs, together with the LogCat output you get from the library. If you can do a tcpdumpon your PC it would be the best thing to debug such scenarios. Before doing that:
* Are you sure that you are contacting the correct path on your server?
* Are there any firewalls in between which may block the traffic? E.g. the integrated firewall on your PC..

**Comment by alexbbb** [comment]
Closing this this ticket as there's no response or evidence of a bug in the library.

**Comment by ryanzulham** [comment]
i have same problem please anwser
Could not find method java.net.HttpURLConnection.setFixedLengthStreamingMode, referenced from method com.alexbbb.uploadservice.HttpUploadTask.upload

**Comment by gotev** [comment]
Please post Library version you use and a snippet reproducing the error

**Comment by ryanzulham** [comment]
@alexbbb 
this library version
com.alexbbb:uploadservice:1.5

this logcat
I/dalvikvm: Could not find method java.net.HttpURLConnection.setFixedLengthStreamingMode, referenced from method com.alexbbb.uploadservice.HttpUploadTask.upload
W/dalvikvm: VFY: unable to resolve virtual method 29282: Ljava/net/HttpURLConnection;.setFixedLengthStreamingMode (J)V
D/dalvikvm: VFY: replacing opcode 0x6e at 0x0055

**Comment by gotev** [comment]
That issue was fixed in a previous release. I do not support or maintain older versions. I highly recommend you to upgrade to the latest 3.1 release which is the most stable and updated. Check the Setup wiki page for detailed migration instructions and the other pages for actual examples of how to use the new library version.

**Comment by ryanzulham** [comment]
OK Thanks @gotev i try it
