### ISSUE TITLE
Upgrading from 1.4 to 1.6 causes ClassNotFoundException

### ISSUE THREAD

**Issue by loevaljh** [alexbbb/android-upload-service#63]
Hi,
I'm trying out Android and use your awesome library (1.4) to upload some files. It's amazing!

Today I tried to upgrade to the newest version (1.6). 
After some code refactor, e.g using a UploadNotificationConfig object and renaming AbstractUploadServiceReceiver to UploadServiceBroadcastReceiver, it compiles successfully again.

However the app crashes complaining the ClassNotFoundException. And I think it's caused by
inconsistent library versions. The v7 version I'm using is com.android.support:appcompat-v7:23.1.0
Do you enforce a specific version in the upgrade?

Here is the error:
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.widget.TintManager" on path

Thanks!

**Comment by Isaackingston** [comment]
Changing the dependency to this  'com.android.support:appcompat-v7:23.1.1' fixed this issue. Please check.

**Comment by alexbbb** [comment]
@Isaackingston your analysis is correct. I upgraded all the library dependencies to the latest available versions, and I'm using appcompat 23.1.1: https://github.com/alexbbb/android-upload-service/blob/master/uploadservice/build.gradle#L32
