### ISSUE TITLE
how to change file content type from Application/octet-stream to image/jpeg ?

### ISSUE THREAD

**Issue by azizimusa** [alexbbb/android-upload-service#64]
By default it set the image with the content type of Application/octet-stream. How do I change it?

**Comment by alexbbb** [comment]
Use [this method](http://alexbbb.github.io/android-upload-service/javadoc/com/alexbbb/uploadservice/MultipartUploadRequest.html#addFileToUpload-java.lang.String-java.lang.String-java.lang.String-java.lang.String-).
