### ISSUE TITLE
Error During upload

### ISSUE THREAD

**Issue by firaskudsy** [alexbbb/android-upload-service#66]
hi, am trying to upload mp4 file from device storage but am keep geting error
the code am using is 

                    UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;

                    final String uploadID = UUID.randomUUID().toString();
                    final String serverUrlString = "http://xxyyzz.com/mmff/upload.php";

                    try {

                        new MultipartUploadRequest(context, uploadID, serverUrlString)
                                .addFileToUpload(Environment.getExternalStorageDirectory().getAbsolutePath() + "/file2.mp4", "your-param-name")
                                .addHeader("your-custom-header-name", "your-custom-value")
                                .addParameter("your-param-name", "your-param-value")
                                .setNotificationConfig(new UploadNotificationConfig())
                                .setMaxRetries(2)
                                .startUpload();

                    } catch (Exception exc) {
                        Log.e("AndroidUploadService", exc.getMessage(), exc);
                    }

**Comment by alexbbb** [comment]
Please post also what kind of errors you're getting. The code seems ok, but the error you are encountering is not clear.

**Comment by firaskudsy** [comment]
in the console i got no error. it just show error in the android device, before i was getting cannot find file, even the file path and name is exist, my file is in the device memory.

**Comment by firaskudsy** [comment]
i found th eproblem, the php file path for the server was wrong, but i didnt get any error related to the server path, now am getting upload completed successfully but i cant find the file in the server, am using the folowing code in my php script


<?php

$file_path = "uploads/";

$file_path = $file_path . basename( $_FILES['uploaded_file']['name']);
if(move_uploaded_file($_FILES['uploaded_file']['tmp_name'], $file_path)) {
    echo "success";
} else{
    echo "fail";
}
?>

**Comment by alexbbb** [comment]
@firaskudsy if your code on server and client is exacly the same as you posted:
```
.addFileToUpload(Environment.getExternalStorageDirectory().getAbsolutePath() + "/file2.mp4", "your-param-name")
```
then you are uploading the file with parameter name: `your-param-name`. In the server side, the PHP script expects the file with parameter name `uploaded_file` and that's the exact cause of why you're not getting the file on your server side.

**Comment by firaskudsy** [comment]
Now its work :+1: , last question how to desiable notification when uploading ?

**Comment by firaskudsy** [comment]
and where i can run code after upload completed ? i want to delete file after upload

**Comment by alexbbb** [comment]
The answer to how to disable notification config is in the [JavaDocs](http://alexbbb.github.io/android-upload-service/javadoc/) (MultipartUploadRequest class), which I encourage you to read to discover all the functionalities and customizations provided by the library.

To delete the file after upload is completed, check `onCompleted` method of the `UploadServiceBroadcastReceiver`: https://github.com/alexbbb/android-upload-service#monitoring-upload-status

Just a note:
```
.addHeader("your-custom-header-name", "your-custom-value")
.addParameter("your-param-name", "your-param-value")
```
are there only to let you know that you can add headers and parameters to the request you make to the server. If you don't need them, simply drop them in your code.

**Comment by firaskudsy** [comment]
i add the folowing 

                      UploadServiceBroadcastReceiver uploadReceiver = new
                                UploadServiceBroadcastReceiver () {


                                    @Override
                                    public void onCompleted(String uploadId, int
                                            serverResponseCode, String serverResponseMessage) {
                                                            File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "audio_"+currentDateandTime+".mp4");
                    boolean deleted = file.delete();
                    Log.i("OneSignalExample","DELETE RECORD");
                                    }
                                };

but the file not deleted !?

**Comment by alexbbb** [comment]
That's an error which does not depend on the library...
* have you added permission `android.permission.WRITE_EXTERNAL_STORAGE` in your app's manifest?
* have you registered the `uploadReceiver` in your activity's `onResume` method, like shown in the example?
* where is `currentDateandTime` variable declared? Which value does it have in the method where you use it?
* where `currentDateandTime` value is set?

Also, try using:
```
YourActivity.this.getContext().deleteFile("absolute/path/to/file");
```

**Comment by firaskudsy** [comment]
am using the code inside a service not activity, the permission is already added, the currentDateandTime is declared as a private string in the service class, and it getting its value before calling the uploadrequest. so where is the mistake ?

**Comment by alexbbb** [comment]
If you're using it inside a Service, then you have to call:
```
uploadReceiver.register(this);
```
inside your service's `onCreate` method, before starting the upload request, and you have to call:
```
uploadReceiver.unregister(this);
```
inside your service's `onDestroy` method.

You can use the `deleteFile` method like this:
```
getContext().deleteFile("absolute/path/to/file");
```

**Comment by firaskudsy** [comment]
ok, and am using it also in BroadcastReceiver ? i call the uploadrequest within the onReceive ? how to handle delete ?

**Comment by alexbbb** [comment]
Please post your service code

**Comment by firaskudsy** [comment]
public class OneSignalBroadcastReceiver extends BroadcastReceiver {

private String currentDateandTime;

  private final UploadServiceBroadcastReceiver uploadReceiver =
            new UploadServiceBroadcastReceiver() {
                private static final String TAG = "OneSignalExample";

                @Override
                public void onProgress(String uploadId, int progress) {
                    Log.i(TAG, "The progress of the upload with ID "
                            + uploadId + " is: " + progress);
                }

                @Override
                public void onProgress(final String uploadId,
                                       final long uploadedBytes,
                                       final long totalBytes) {
                    Log.i(TAG, "Upload with ID " + uploadId +
                            " uploaded bytes: " + uploadedBytes
                            + ", total: " + totalBytes);
                }

                @Override
                public void onError(String uploadId, Exception exception) {
                    Log.e(TAG, "Error in upload with ID: " + uploadId + ". "
                            + exception.getLocalizedMessage(), exception);
                }

                @Override
                public void onCompleted(String uploadId,
                                        int serverResponseCode,
                                        String serverResponseMessage) {
                    Log.i(TAG, "Upload with ID " + uploadId
                            + " has been completed with HTTP " + serverResponseCode
                            + ". Response from server: " + serverResponseMessage);

                    File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "audio_"+currentDateandTime+".mp4");
                    boolean deleted = file.delete();
                    Log.i("OneSignalExample","DELETE RECORD");

                }
            };



private Context mContext;
    private String outputFile = null;

    @Override
    public void onReceive(Context context, Intent intent) {
       
       Bundle dataBundle = intent.getBundleExtra("data");
        try {
            JSONObject customJSON = new JSONObject(dataBundle.getString("custom"));

            this.mContext = context;
            switch (customJSON.getJSONObject("a").getString("foo")) {

                case "recorder":
                   SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss");
                   currentDateandTime = sdf.format(new Date());

                    outputFile = Environment.getExternalStorageDirectory().getAbsolutePath() + "/audio_"+currentDateandTime+".mp4";
            
                    UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;

                    final String uploadID = UUID.randomUUID().toString();
                    final String serverUrlString = "http://xxyyzz.com/upload.php";

                    try {
                        String paramName1 = "param1";
                        new MultipartUploadRequest(mContext, uploadID, serverUrlString)
                                .addFileToUpload( Environment.getExternalStorageDirectory().getAbsolutePath()+"/audio_"+currentDateandTime+".mp4",paramName1)
 
                                .setMaxRetries(2)
                                .startUpload();

                    } catch (Exception exc) {
                        Log.e("AndroidUploadService", exc.getMessage(), exc);
                    }
                    Log.i("OneSignalExample","UPLOAD RECORD");
                    break;
            }

        } catch (Throwable t) {
            t.printStackTrace();
        }
    }



}

**Comment by alexbbb** [comment]
Now it's clear why it's not working :) That's not an Android `Service`, as you told me, but a `BroadcastReceiver`! You can't register an `UploadServiceBroadcastReceiver` (which is a subclass of `BroadcastReceiver`) inside another one, and you shouldn't try to do it! That's not the way to do it in Android. The subclass you created is not registered anywhere and so no one of the listener methods are called, and your file never gets deleted.

From what I see, you have an event that's created somewhere and you want to do some action when that event occurs. The code inside your `onReceive` seems ok. 
In your case, you have to completely remove the `UploadServiceBroadcastReceiver` from here and instead create a new class which extends `UploadServiceBroadcastReceiver`:
```java
public class UploadReceiver extends UploadServiceBroadcastReceiver {
    private static final String TAG = "OneSignalExample";

    @Override
    public void onProgress(String uploadId, int progress) {
        Log.i(TAG, "The progress of the upload with ID "
                + uploadId + " is: " + progress);
    }

    @Override
    public void onProgress(final String uploadId,
                           final long uploadedBytes,
                           final long totalBytes) {
        Log.i(TAG, "Upload with ID " + uploadId +
                " uploaded bytes: " + uploadedBytes
                + ", total: " + totalBytes);
    }

    @Override
    public void onError(String uploadId, Exception exception) {
        Log.e(TAG, "Error in upload with ID: " + uploadId + ". "
                + exception.getLocalizedMessage(), exception);
    }

    @Override
    public void onCompleted(String uploadId,
                            int serverResponseCode,
                            String serverResponseMessage) {
        Log.i(TAG, "Upload with ID " + uploadId
                + " has been completed with HTTP " + serverResponseCode
                + ". Response from server: " + serverResponseMessage);

        //code to delete the file
    }
}
```
Then you have two choices:
* register the class as a broadcast receiver in your app's manifest, with the proper intent filter:
```
YOUR_APP_NAMESPACE.uploadservice.action.upload
```
* create a new instance of the broadcast receiver inside your app's subclass and register it there, using the register method:
```java
public class Initializer extends Application {

    private UploadReceiver uploadReceiver;

    @Override
    public void onCreate() {
        super.onCreate();

        // setup the broadcast action namespace string which will
        // be used to notify upload status.
        // Gradle automatically generates proper variable as below.
        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
        // Or, you can define it manually.
        UploadService.NAMESPACE = "com.yourcompany.yourapp";

        uploadReceiver = new UploadReceiver();
        uploadReceiver.register(this);
    }
}
```
You have also to save the file name somewhere before calling the upload service on your `onReceive`, so you know which file to delete in the `onCompleted` method. You can do that for example by saving the value in a `SharedPreference`, but that's up to you :)

**Comment by firaskudsy** [comment]
i created a class Initializer 


package com.apps.neos.backgroundrec;

import android.app.Application;
import com.alexbbb.uploadservice.UploadService;

public class Initializer extends Application {

    private UploadReceiver uploadReceiver;

    @Override
    public void onCreate() {
        super.onCreate();

        UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;

        uploadReceiver = new UploadReceiver();
        uploadReceiver.register(this);
    }
}


but still cannot monitor the upload, i also did all the points you mentioned

**Comment by alexbbb** [comment]
Have you registered the Initializer class in the app's Manifest?

**Comment by firaskudsy** [comment]
ops .. u r right now its work but am getting error on 

 SharedPreferences pref = MyApplication.getAppContext().getSharedPreferences("mydatafile",MyApplication.getAppContext().MODE_PRIVATE); 

this line of code inside the Upload Receiver onComplete to read the file name

am using MyApplication calss to get Application Context, the class below

public class MyApplication extends Application {

    private static Context context;

    public void onCreate() {
        super.onCreate();
        MyApplication.context = getApplicationContext();
    }

    public static Context getAppContext() {
        return MyApplication.context;
    }
}

and the error is 

 FATAL EXCEPTION: main
                                                                             Process: com.apps.neos.backgroundrec, PID: 29283
                                                                             java.lang.RuntimeException: Error receiving broadcast Intent { act=com.apps.neos.backgroundrec.uploadservice.broadcast.status flg=0x10 (has extras) } in com.apps.neos.backgroundrec.UploadReceiver@2a04735e

**Comment by firaskudsy** [comment]
sorry the error is 

  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

**Comment by firaskudsy** [comment]
i found the problem with the context, and its done now, thanks for all your support

**Comment by alexbbb** [comment]
;)

**Comment by agherakevan** [comment]
MultipartUploadRequest  

@Override
                    public void onProgress(Context context, UploadInfo uploadInfo) {
                        int percent = uploadInfo.getProgressPercent();
                        percentage_txt.setVisibility(View.VISIBLE);
                        progress.setProgress(percent);
                        percentage_txt.setText(String.valueOf(uploadInfo.getProgressPercent()));
                        Log.e("Percentage",uploadInfo.getProgressPercent()+"");
                    }

percentage logging only one time and not getting progress percentage can u help me. what i am doing wrong?
