### ISSUE TITLE
.

### ISSUE THREAD

**Issue by koderbober** [alexbbb/android-upload-service#75]

**Comment by alexbbb** [comment]
Version 1.6 has the following dependecies:
```
compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.android.support:support-v4:23.1.1'
```
I suggest you to upgrade your project to those versions, instead of using the older 1.5 release. I've seen that you closed the ticket. Have you solved the issue?

**Comment by koderbober** [comment]
At the time, when I wrote this comment, the problem is really solved. I don't understand exactly how. It's magic. :) And I still use 1.5. When using the library has had a problem with other libraries and it work now. And thanks for reply anyway!

**Comment by alexbbb** [comment]
When that kind of dependency problems happens, gradle allows you to force the usage of a specific library version. Check this answer: http://stackoverflow.com/a/24532623 
If you use v22 in your project, you can try including 1.6 and forcing that dependency version. I thiunk that it will not cause any problem to android upload service. Never tried it personally, but you can try it if you want to upgrade to 1.6 or newer releases without having conflicts.

**Comment by koderbober** [comment]
This is interesting, I will try. Thank you very much for your help!

**Comment by alexbbb** [comment]
You're welcome. Please let me know if it works, so I could add that info in the readme and be helpful to other users, too :)

**Comment by koderbober** [comment]
Yes, it's work! compileSdkVersion 22 and force support library v23! And as a result I use uploadservice v1.6! Great!

**Comment by alexbbb** [comment]
Great! Could you please post the exact gradle snippet which you used?

**Comment by koderbober** [comment]
I just added this:

    configurations.all {
        resolutionStrategy {
            force 'com.android.support:support-v4:23.+'
            force 'com.android.support:appcompat-v7:23.+'
        }
    }

    dependencies {
        ...
        compile 'com.alexbbb:uploadservice:1.6'
    }
